list = []

list.append(-1)
list.append(-1)
list.append(-1)
list.append(-1)
list.append(-1)
list.append(-1)
list.append(-1)
list.append(-1)
list.append(-1)
list.append(-1)
list.append(-1)

print(list[1])
print(list[2])
print(list[3])
print(list[4])
print(list[5])
print(list[6])
print(list[7])
print(list[8])
print(list[9])
print(list[10])
